### PR TITLE
New/rewritten typings

### PR DESCRIPTION
**Pull request by Codex-**
The original typings are incorrect in many ways (such as not extending EventEmitter, meaning that consumers of these typings cannot access the typed methods provided by EventEmitter), I have written these again from scratch.

The original typings author has since deleted or removed his github page, leaving these unmaintained.

This style of typings and test methods are inspired by https://github.com/sindresorhus/typescript-definition-style-guide

I've based what has been exposed as public based on the documentation, please read over these and confirm my interpretation is correct, if not let me know what needs to be changed :)

I also suggest a major version bump due to the typings being rewritten being a breaking change (Current consumers of the typings have likely had to do hacky things to get the typings exposed for the extended emitter etc.)

### CODE REVIEW

**Comment by Codex-** [comment]
Unsure why the primary runner step executes successfully but the second with the differing node versions fails, tested both versions locally and all passed.

**Comment by jessetane** [comment]
```
npm ERR! notarget No matching version found for create-error-class@3.0.33
```

^ from https://travis-ci.org/jessetane/queue/jobs/466276824, does it mean anything to you? (i have no idea)

**Comment by jessetane** [comment]
i don't know ts well but thanks for your work and the explanation. good thinking on major version, i will bump it

**Comment by jessetane** [comment]
i tried rerunning at travis but same error

**Comment by Codex-** [comment]
Managed to replicate it locally in linux only, not sure what is causing the error though. Only happens when using Node 11, but the packages being targeted specify `"node": ">=0.10.0"` so there's no reason why it should be failing. 

Will look into it when I can more.

To replicate on linux on linux just follow the travis output commands and you'll stumble across it:
```
430 error code ETARGET
431 error notarget No matching version found for is-retry-allowed@1.1.1
432 error notarget In most cases you or one of your dependencies are requesting
432 error notarget a package version that doesn't exist.
```

**Comment by Codex-** [comment]
Passing now :)

**Pull request merged**
