### PR TITLE
promises support

### PR DESCRIPTION
**Pull request by kwolfy**
This library is cool but need promises support. 

Thanks!

### CODE REVIEW

**Comment by jessetane** [comment]
Why not just use `Promise.all`?

**Comment by kwolfy** [comment]
@jessetane

We have promised function that return some data for queue job
```javascript
const getSomeDataPromised = () => {
  return new Promise((resolve, reject) => {
    resolve('Data');
  });
};
```

Now we should create job like that

```javascript
q.push((cb) => {
  getSomeDataPromised()
     .then(result => cb(null, result))
     .catch(err => cb(err || "error");
});
```

I offer

```javascript
q.push(() => getSomeDataPromised());
```


So, where could i use Promise.all ?

**Comment by jessetane** [comment]
What I mean is that if you are not using callbacks then you probably don't need this library:
```
Promise.all([
  getSomeDataPromised(),
  getSomeOtherDataPromised()
]).then(() => {
  // all done
}).catch(err => {
  // bad stuff
})
```

If you need concurrency control check out:
http://bluebirdjs.com/docs/api/promise.map.html

**Comment by kwolfy** [comment]
Of course, but in real life it will be code duplication with then, catch.

**Comment by jessetane** [comment]
Sorry, not trying to be a pain, and I'm still open to this, I just don't understand the use case. Would you be willing to give a complete example of what you mean? Maybe using something like [runkit](https://npm.runkit.com/queue)?

**Comment by kwolfy** [comment]
```javascript

const Promise = require("bluebird");
const queue = require("queue")

const getOne = () => {
    return new Promise((res, rej) => {
        res("one");
    });
};

const getTwo = () => {
    return new Promise((res, rej) => {
        res("two");
    });
};

const getMixed = (one, two) => {
    return new Promise((res, rej) => {
        res(one + two);
    });
};


const q = queue();

const results = [];


// now
q.push((cb) => {
    getOne()
        .then((one) => {
            results.push(one);
            cb();
        })
        .catch(err => cb(err || "ERROR"));
});

q.push((cb) => {
    getTwo()
        .then((two) => {
            results.push(two);
            cb();
        })
        .catch(err => cb(err || "ERROR"));
});

//My offer

q.push(() => getOne());
q.push(() => getTwo());



// now

q.push((cb) => {
    Promise
        .all([getOne(), getTwo()])
        .then(([one, two]) => getMixed(one, two))
        .then(mixed => {
            results.push(mixed);
            cb();
        })
        .catch(err => cb(err || "ERROR"));
});


//With async await

q.push(() => async () => {
    const [one, two] = await Promise.all([getOne(), getTow()]);
    
    return getMixed(one, two);
})




```

**Comment by jessetane** [comment]
You example doesn't explain why you would use `Promise.all` AND queue - why not just use one or the other?

**Comment by jessetane** [comment]
Basically if you have promises, use Promise.all, if you have callbacks, use queue

**Comment by kwolfy** [comment]
So, i just found out that queue doesn't support full async mode and just implements it by setting timeout i'd mixed up timeout and delay, so are you planing to make real async in queue ?

**Comment by jessetane** [comment]
I honestly have no idea what you are talking about

**Comment by TomKaltz** [comment]
An alternative is to use Bluebird.mapSeries.  The downside to that is that we can't stop the processing of the queue with mapSeries.  If this module supported Promises it would be like mapSeries but we could have the rich queue options like start, stop, end as well as all the array-like methods.

**Comment by jessetane** [comment]
@TomKaltz thanks for chiming in. In my opinion (just an opinion!) Promises make my code harder to understand, harder to debug and less performant than simple callbacks and so I don't use them. That said, @kwolfy's patch isn't terribly invasive (though it needs a bit of cleanup) so I'm open to it if others feel strongly that it should be included. Reopening for a while to see if anyone else has strong feelings either way. Please add opinions and concrete use cases if you have them!

**Comment by jonnyt886** [comment]
@jesstane I'd be interested in this. I use promises throughout my code but Bluebird's implementation is no good for me.

My use case is processing input (a rather large file containing one JSON object per line). If I load the whole file and call `Promise.map` then the entire file will be in memory, which is not workable for me. With `queue` I get much more control over what is loaded when, and I can continue to add things to the queue in one part of my code while it consumes them (asynchronously), and then once I've finished adding things to my queue, I use `.on()` to resolve a Promise and then complete my processing.

**Comment by jessetane** [comment]
Hi all, sorry for the delay on this, I will have a chance to review tomorrow

**Comment by jessetane** [comment]
Published as 4.3.1, thanks for your work

**Pull request merged**
