### PR TITLE
Improve concurrency tests further

### PR DESCRIPTION
**Pull request by sdesalas**
I improved the concurrency tests a bit. 

This way you can check that concurrency is applied to more than 2 jobs (4 in total), before its reduced down to 1.

Still passes, but this way it covers an extra scenario where you want to maintain concurrency while consuming extra jobs.

### CODE REVIEW

**Comment by sdesalas** [comment]
The failing test (before changes to #38) executes as follows:

```
not ok 8 should be equal
  ---
    operator: equal
    expected: 'three'
    actual:   'six'
    at: Queue.onend (/index.js:184:5)
  ...
not ok 9 should be equal
  ---
    operator: equal
    expected: 'four'
    actual:   'three'
    at: Queue.onend (/index.js:184:5)
  ...
not ok 10 should be equal
  ---
    operator: equal
    expected: 'five'
    actual:   'four'
    at: Queue.onend (/index.js:184:5)
  ...
not ok 11 should be equal
  ---
    operator: equal
    expected: 'six'
    actual:   'five'
    at: Queue.onend (/index.js:184:5)
  ...
```

In other words, still replicating the timeouts after concurrency is dropped 1, instead of sending jobs one-by-one as would be expected.

**Comment by jessetane** [comment]
I'm not grasping this yet, doesn't [this](https://github.com/jessetane/queue/blob/b5b47d85eb4c785e487beceb37455063ffdcc0f5/test/concurrent.js#L40) already prove concurrency of 2 is working?

**Comment by sdesalas** [comment]
I think the test in there proves that concurrency of 2 works, but it doesn't prove that it works past the initial 2 jobs. If for whatever reason the implementation code changes so the concurrency is compromised past this initial batch (of 2), the tests as they currently stand won't capture it. 

This stuff is confusing as hell (and hard to explain). I'm not sure what you mean by pointing to job `five`, but past job `three` the tests in there will only run one job at a time. So you cant test that concurrency is being maintained. 

I could be wrong though. But I dont think so.

**Comment by jessetane** [comment]
It's late here, will think about it tomorrow and get back to you. Thanks for the explanation.

**Comment by jessetane** [comment]
Maybe it would be easier to reason about if we had multiple tests in this file?

**Comment by sdesalas** [comment]
Put back original `concurrent` test, added `concurrent with changes` test.

I've also added `start` and `end` job markers that make it easier to understand what is going on.

**Pull request closed without merging**
