### PR TITLE
Update node packages to resolve security vulnerabilities.

### PR DESCRIPTION
**Pull request by Codex-**
This PR is to address the security vulnerabilities in dev-dependant packages in Queue, running `npm audit` returns:
`found 16 vulnerabilities (6 low, 5 moderate, 4 high, 1 critical) in 1444 scanned packages`

Despite these being only dev dependencies, it's best to keep this repo in a healthy secure state.

This PR is based off current master, once the other is accepted and merged I'll update and merge the new master into the branch, and resolve any merge conflicts etc.

Also in regards to the `istanbul` package which is used for code coverage, this has been superseded by `nyc` from the same authors, as they have intentions to redesign the purpose and functionality of `istanbul`. Consider changing to use `nyc` (we were using it too and have been switching over, it's fairly painless). See: https://www.npmjs.com/package/nyc & https://github.com/istanbuljs/nyc/issues/524

You can generate the same coverage reports and satisfy the coveralls requirements.

### CODE REVIEW

**Comment by jessetane** [comment]
ok, #54 has been merged if you wanna rebase

**Comment by Codex-** [comment]
Good to go :)

**Comment by jessetane** [comment]
thanks. would you mind terribly squashing these commits? it would make the history a bit easier to follow

**Comment by Codex-** [comment]
> thanks. would you mind terribly squashing these commits? it would make the history a bit easier to follow

Including the merge commits or just the last two?

**Comment by jessetane** [comment]
i mean logically it's all kinda one thing, right? i'd suggest this be a single commit unless you feel strongly otherwise

**Comment by jessetane** [comment]
the last two are fine, it's the merge commits that bug me - they just don't seem to add anything useful

**Comment by jessetane** [comment]
basically, the first 3 commits would get squashed with 45dc43c

**Comment by jessetane** [comment]
i dunno, whatever you think is easiest to read. it's just nice to have a concise sequence of commits with clear messages about what changed rather than artifacts from someone's development workflow

**Comment by Codex-** [comment]
Yeah I understand what you're saying, looking at it now to see if git will play ball

**Comment by jessetane** [comment]
cool, thx. normally what i do is rebase my feature or fix branch onto master as other commits land there. no extraneous merge commits get added and if there is a conflict it can be fixed interactively

**Comment by Codex-** [comment]
That's reasonable, cheer 👍

**Comment by jessetane** [comment]
heh, looks like it all stuck around anyhow. oh well, we tried 🤷

**Comment by jessetane** [comment]
released as 5.0.0, thanks for your work

**Comment by Codex-** [comment]
Awesome thanks! One day npm will update

**Pull request merged**
