### PR TITLE
Change end event behavior

### PR DESCRIPTION
**Pull request by krjj**
wait for all pending tasks to complete before end event is emitted.

### CODE REVIEW

**Comment by jessetane** [comment]
Hey thanks for the patch. Can you give an example that explains why this change is needed?

**Comment by ScreamZ** [comment]
@krjj @jessetane any update on this ?

**Comment by jessetane** [comment]
If you care to wait until all pending jobs complete, why bother calling this method at all?

**Comment by jessetane** [comment]
Closing as I don't understand the motivation for this, reopen if you want to discuss

**Pull request closed without merging**
